api:
    swagger-host: localhost:8080
    bucket-url: https://storage.googleapis.com/jugoterapia/
    host: localhost
spring:
    data:
        mongodb:
            database: jugoterapia
            username: jugoterapiaUser
            password: jugoterapiaPassword
