api:
    bucket-url: https://storage.googleapis.com/jugoterapia/
    host: localhost
swagger:
    server: "http://localhost:8080"
spring:
    data:
        mongodb:
            #Change the database name and or credentials to match your local setup
            database: jugoterapia
            username: jugoterapiaUser
            password: jug0t3r4p14DB
