api:
    bucket-url: https://storage.googleapis.com/jugoterapia/
    host: localhost
spring:
    data:
        mongodb:
            #Change the database name and or credentials to match your local setup
            database: jugoterapia
            username: jugoterapiaUser
            password: jugoterapiaPassword
