name: Run Tests
on:
  push:
    branches: [ "main", "feature/38" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      mongodb:
        image: mongo:5.0.24
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: jugoterapia
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongo
          --health-interval 20s
          --health-timeout 5s
          --health-retries 10
    steps:
      - uses: actions/checkout@v3
      - name: Set up MongoDB
        run: |
          importing data "Waiting for MongoDB to start..."
          mongo --version
          echo "MongoDB ready!"
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew --version